### ISSUE TITLE
Server Crash on Punching

### ISSUE THREAD

**Issue by fzzyhmstrs** [LCLPYT/illusory-walls#5]
Getting a server crash when a player punches an illusory wall. Player was in creative mode when it happened. This appears to be related to the usage of the `@Environment` annotation in a class initializer. Per the Fabric docs, this is a classic case that will cause an error:

```
When the annotated element is removed, bytecode associated with the element will not be removed. For example, if a field is removed, its initializer code will not, and will cause an error on execution.
```

Logs:

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2024-04-17 18:54:47
Description: Exception in server tick loop

java.lang.NoSuchFieldError: fadeStartMs
    at work.lclpnet.illwalls.entity.StructureEntity.<init>(StructureEntity.java:42)
    at net.minecraft.entity.EntityType.create(EntityType.java:544)
    at net.minecraft.entity.EntityType.create(EntityType.java:409)
    at net.minecraft.entity.EntityType.spawn(EntityType.java:397)
    at work.lclpnet.illwalls.entity.IllusoryWallEntity.fade(IllusoryWallEntity.java:161)
    at work.lclpnet.illwalls.wall.SimpleIllusoryWallManager.fadeWallAtIfPresent(SimpleIllusoryWallManager.java:32)
    at work.lclpnet.illwalls.IllusoryWallsMod.lambda$onInitialize$1(IllusoryWallsMod.java:119)
    at net.fabricmc.fabric.api.event.player.AttackBlockCallback.lambda$static$0(AttackBlockCallback.java:51)
    at net.minecraft.server.network.ServerPlayerInteractionManager.handler$cjn000$fabric-events-interaction-v0$startBlockBreak(ServerPlayerInteractionManager.java:3563)
    at net.minecraft.server.network.ServerPlayerInteractionManager.processBlockBreakingAction(ServerPlayerInteractionManager.java)
    at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerAction(ServerPlayNetworkHandler.java:1083)
    at net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket.apply(PlayerActionC2SPacket.java:42)
    at net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket.apply(PlayerActionC2SPacket.java:8)
    at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:22)
    at net.minecraft.server.ServerTask.run(ServerTask.java:18)
    at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156)
    at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23)
    at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:782)
    at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:164)
    at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130)
    at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:764)
    at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:758)
    at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:115)
    at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:742)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:675)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by LCLPYT** [comment]
Hi, thank you for reporting the issue.
I'll look into it asap

**Comment by LCLPYT** [comment]
You are indeed right. The StructureEntity that is spawned when an IllusoryWallEntity is broken had an initializer for a client only field.
Interestingly enough, that didn't happen with by Java version.
I fixed it nonetheless.

This will be part of the next release. I'll publish it soon on Modrinth and GitHub
